### ISSUE TITLE
Default required GAP version in package template.

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/PackageMaker#22]
The current behaviour is that the template puts GAP 4.6 as required version. I suggest to change it to the version of GAP that is used to run PackageMaker.

**Comment by fingolfin** [comment]
Hm... but what about people who run PackageMaker with the GAP development version? It has version `4.dev`...

**Comment by alex-konovalov** [comment]
Then what - just manually update the minimal required version of GAP to the last public major release? E.g. now it has "4.8", and that sounds fine.

**Comment by fingolfin** [comment]
For now my plan is to simply keep this in sync with the GAP version required for PackageMaker itself.
