### ISSUE TITLE
Licence For Generated Code

### ISSUE THREAD

**Issue by jesselansdown** [gap-system/PackageMaker#32]
Could you grant explicit permission to use the code generated by the package under other licences in order to allow authors who use PackageMaker to choose the licence for their package?

**Comment by fingolfin** [comment]
I am happy with allowing relicensing the code to any OSI-certified and GPL-compatible license (I'd argue that the latter is required anyway for a GAP package). I will add a corresponding license granting this right to PackageMaker when I am back from vacation.

**Comment by fingolfin** [comment]
Some late update on this: Some interpretations of the GPL (e.g. that which the FSF itself takes) would imply that any code written in the GAP language automatically must be GPL licensed. If one takes that point of view (and as I said, apparently at least the FSF takes it), it doesn't matter what I personally allow regarding to the licensing of the generated code.

That said, I still should add that explicit (re)licensing info to `PackageMaker`, but these days, I don't find time to work on it at all.
