### ISSUE TITLE
Webpage says Version 0.8, but linked doc says Version 0.9

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/PackageMaker#42]
The title pretty much says it all, the refer to webpage is:

https://gap-system.github.io/PackageMaker/

The release date of 0.8 also appears to be after that of 0.9 in the doc.

**Comment by james-d-mitchell** [comment]
Yes, indeed, that's what I said too :)

**Comment by fingolfin** [comment]
This will automatically be fixed by the next release.

**Comment by fingolfin** [comment]
Resolved by version 0.9.
