### ISSUE TITLE
The generated C++ kernel module is incompatible with stable-4.10

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/PackageMaker#43]
It looks like the C++ kernel module generated by `PackageMaker` is incompatible with GAP 4.10. 

~~~~
error: cannot initialize a member subobject of type
      'Obj (*)()' (aka 'unsigned long long **(*)()') with an lvalue of type
      'Obj (Obj)' (aka 'unsigned long long **(unsigned long long **)'):
      different number of parameters (0 vs 1)
    GVAR_FUNC(TestCommand, 0, ""),
~~~~

Maybe the same issue as experienced by the Semigroups package recently, due to the change of signature for `GVAR_FUNC`?

**Comment by james-d-mitchell** [comment]
On second thoughts, I don't think this is related to the recent issue we experienced with Semigroups.

**Comment by fingolfin** [comment]
Hmm, I can't reproduce this here. Perhaps it requires a specific compiler or so?

**Comment by fingolfin** [comment]
I cannot reproduce this with current `master` branch with GCC 7 and with clang. If you still experience this problem, I'd appreciate if you reopened this issue with some additional details, e.g. the full output of `make` and perhaps some information on the compiler and build environment. Thanks!

**Comment by fingolfin** [comment]
Err, 3962eb8f2f5cf3b774375336c60cea5f09cd2101 incorrectly references this issue, it was meant to reference #7
