### ISSUE TITLE
Kernel ext: allow user to specify whether it is required or optional

### ISSUE THREAD

**Issue by fingolfin** [gap-system/PackageMaker#7]
Right now, it is always "optional", i.e. loading the package without it is possible. But for some applications, the extensions is mandatory.

**Comment by ChrisJefferson** [comment]
I would switch to mandatory by default (I just hit this problem).

Perhaps print a warning about compiling it, so then a user can see that message and either delete it, or make it an Error, but at least knows to go looking (I just got confused why my new package wasn't working :) )

**Comment by fingolfin** [comment]
Resolved by 3962eb8f2f5cf3b774375336c60cea5f09cd2101
